# Generated by Django 5.1.1 on 2024-09-28 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField()),
                ('wi_fi_availability', models.CharField(choices=[('No', 'Not Available'), ('Yes', 'Available')], max_length=3)),
                ('socket_availability', models.CharField(choices=[('No', 'Not Available'), ('Yes', 'Available')], max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('official_name', models.CharField(max_length=100)),
                ('registered_address', models.TextField()),
                ('company_registration_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Company Names',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_choice', models.CharField(choices=[('EC', 'Economy Class'), ('LK', 'Luxury Class'), ('BK', 'Business Class'), ('VP', 'VIP Class')], max_length=2)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bus')),
            ],
            options={
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyname'),
        ),
    ]
