# Generated by Django 5.1.1 on 2024-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_type_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type_place',
            field=models.CharField(choices=[('ECO', 'Economy'), ('STD', 'Standard'), ('LUX', 'Luxury'), ('PRS', 'President')], max_length=3),
        ),
    ]
